#pragma once

#define ENCODER_RESOLUTION 4

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "6qbrr/wObbxP"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_TIME_TO_MAX 64
#define MOUSEKEY_MAX_SPEED 40
#define MOUSEKEY_FRICTION  1
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_INERTIA_SLOW_DIVISOR 2
